spring.application.name=proyecto-entregable

spring.datasource.url=jdbc:mysql://10.12.46.165:3306/ddbb_eda_MoyaJuan?useSSL=false&serverTimezone=UTC
spring.datasource.username=fila4
spring.datasource.password=Osito+123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
